"'Settings(com)' As CanvasComponent":
    Currentscreen: ="Text"
    Fill: =RGBA(0, 0, 0, 0)
    Height: =500
    Settings_menu: |-
        =Table({Title:"HACT User",TargetScreen:App.ActiveScreen})
    Width: =276
    X: =0
    Y: =0
    ZIndex: =1

    Gallery5 As gallery.galleryVertical:
        DelayItemLoading: =true
        Items: ='Settings(com)'.Settings_menu
        Layout: =Layout.Vertical
        LoadingSpinner: =LoadingSpinner.Data
        OnSelect: =true;Navigate(ThisItem.TargetScreen,ScreenTransition.None)
        TemplateSize: =104
        Transition: =Transition.Pop
        ZIndex: =1

        Label14 As label:
            Height: =49
            HoverFill: =Color.LightBlue
            OnSelect: =Select(Parent)
            PaddingLeft: =50
            Size: =15
            Text: =ThisItem.Title
            Width: =256
            X: =10
            Y: =8
            ZIndex: =1

        Icon6 As icon.OptionsList:
            Color: =RGBA(0, 0, 0, 1)
            Height: =32
            Icon: =Icon.OptionsList
            OnSelect: =Select(Parent)
            Width: =20
            X: =20
            Y: =16
            ZIndex: =2

