"'HACT Configuration' As screen":

    Component1_18 As Component1:
        CurrentScreen: ="Configuration"
        Height: =768

    Icon13 As icon.HorizontalLine:
        BorderColor: =RGBA(102, 102, 102, 1)
        BorderThickness: =1
        Color: =RGBA(102, 102, 102, 1)
        Height: =1
        Icon: =Icon.HorizontalLine
        PaddingBottom: =10
        PaddingLeft: =10
        PaddingRight: =10
        PaddingTop: =10
        Width: =1039
        X: =303
        Y: =189
        ZIndex: =2

    Label13 As label:
        Color: =RGBA(0, 18, 107, 1)
        FontWeight: =FontWeight.Bold
        Height: =58
        Size: =20
        Text: ="Supplier Happiness Survey Settings"
        Width: =550
        X: =291
        Y: =132
        ZIndex: =3

    Container3 As groupContainer.manualLayoutContainer:
        DropShadow: =DropShadow.Semilight
        Height: =528
        Width: =596
        X: =318
        Y: =213
        ZIndex: =4

        Rectangle4 As rectangle:
            Fill: =RGBA(237, 237, 237, 1)
            Height: =56
            Width: =596
            ZIndex: =1

        Label15 As label:
            FontWeight: =FontWeight.Semibold
            Height: =34
            Size: =17
            Text: ="Edit Configuration"
            Width: =538
            X: =13
            Y: =8
            ZIndex: =2

        Label16 As label:
            Text: |-
                ="Stakeholder:Supplier"
            Width: =191
            X: =24
            Y: =66
            ZIndex: =3

        Icon14 As icon.HorizontalLine:
            BorderColor: =RGBA(202, 202, 202, 1)
            BorderThickness: =1
            Color: =RGBA(202, 202, 202, 1)
            Height: =1
            Icon: =Icon.HorizontalLine
            Width: =567
            X: =20
            Y: =124
            ZIndex: =4

    Container4 As groupContainer.manualLayoutContainer:
        DropShadow: =DropShadow.Semilight
        Height: =298
        Width: =355
        X: =987
        Y: =213
        ZIndex: =5

        Rectangle4_1 As rectangle:
            Fill: =RGBA(237, 237, 237, 1)
            Height: =56
            Width: =355
            ZIndex: =1

        Label18 As label:
            FontWeight: =FontWeight.Semibold
            Height: =48
            Size: =17
            Text: ="Existing Cofiguration"
            Width: =275
            X: =13
            Y: =8
            ZIndex: =2

        Label16_1 As label:
            Text: |-
                ="Stakeholder:Supplier"
            Width: =191
            X: =13
            Y: =56
            ZIndex: =3

        Icon14_1 As icon.HorizontalLine:
            BorderColor: =RGBA(202, 202, 202, 1)
            BorderThickness: =1
            Color: =RGBA(202, 202, 202, 1)
            Height: =0
            Icon: =Icon.HorizontalLine
            Width: =328
            X: =13
            Y: =114
            ZIndex: =4

        Label16_2 As label:
            Text: |-
                ="Current Year:"
            Width: =191
            X: =13
            Y: =130
            ZIndex: =5

        Icon14_2 As icon.HorizontalLine:
            BorderColor: =RGBA(202, 202, 202, 1)
            BorderThickness: =1
            Color: =RGBA(202, 202, 202, 1)
            Height: =0
            Icon: =Icon.HorizontalLine
            Width: =328
            X: =13
            Y: =186
            ZIndex: =6

        Label19 As label:
            Text: |-
                ="Current Quarter:"
            X: =13
            Y: =206
            ZIndex: =7

        Icon14_3 As icon.HorizontalLine:
            BorderColor: =RGBA(202, 202, 202, 1)
            BorderThickness: =1
            Color: =RGBA(202, 202, 202, 1)
            Height: =0
            Icon: =Icon.HorizontalLine
            Width: =328
            X: =13
            Y: =266
            ZIndex: =8

